# Generated by Django 4.0.5 on 2022-06-10 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import telegram.consts


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('channel_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramInviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=128)),
                ('status', enumfields.fields.EnumField(default='active', enum=telegram.consts.InviteLinkStatus, max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telegram.telegramchannel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_invite_link', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
