# Generated by Django 4.0.5 on 2022-06-10 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0002_region_country_alter_region_name'),
        ('telegram', '0002_telegramchannel_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchannel',
            name='from_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='directions_to', to='directory.region'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='to_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='directions_from', to='directory.region'),
        ),
        migrations.AlterField(
            model_name='telegramchannel',
            name='members',
            field=models.ManyToManyField(related_name='channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='telegraminvitelink',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telegram_invite_links', to='telegram.telegramchannel'),
        ),
        migrations.AlterField(
            model_name='telegraminvitelink',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_invite_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='telegramchannel',
            unique_together={('from_region', 'to_region')},
        ),
        migrations.AlterUniqueTogether(
            name='telegraminvitelink',
            unique_together={('channel', 'user')},
        ),
    ]
